{% set name = "perspective_parquet" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ea67a9a7abdcaa0a5e16f5ddbe8202cbd71db4cc7ff66ee5f8263d42f15ef58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=3.5
  run:
    - python >=3.7
    - jupyterlab >=3.5
    - perspective-python

test:
  imports:
    - perspective_parquet

outputs:
  - name: perspective_parquet
  - name: perspective-parquet
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("perspective_parquet", exact=True) }}

about:
  home: http://github.com/timkpaine/perspective-parquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Parquet file editor in Jupyterlab, built with `perspective`
  description: |
    Parquet file editor in Jupyterlab, built with `perspective`
  dev_url: https://github.com/timkpaine/perspective-parquet

extra:
  recipe-maintainers:
    - timkpaine
